### ISSUE TITLE
BouncingBall FMU export example fails in Ubuntu

### ISSUE THREAD

**Issue by chandramouli6890** [ThummeTo/FMIExport.jl#22]
I am really excited about the possibilities with the FMIExport julia library. I wanted to quickly try to out the `BouncingBall` example. But got into some trouble while running the example.

![image](https://user-images.githubusercontent.com/11978997/210137535-bff30f79-a255-49d7-9378-cf3e949f714e.png)

I am running
* Ubuntu 18.04
* Julia 1.8. 3 (I even tried Julia 1.6.7, but with no luck)

I appreciate any your support from your side

**Comment by ThummeTo** [comment]
Dear @chandramouli6890 ,
I am on this!

Regards!

**Comment by HenningScheufler** [comment]
On windows and julia 1.85 ha the same issue

**Comment by ThummeTo** [comment]
This is under development, but as stated in the readme.md, currently only windows is actively supported & tested.

**Comment by ThummeTo** [comment]
will be fixed in v0.2.0 in #26

**Comment by ThummeTo** [comment]
closed with v0.2.0
