### ISSUE TITLE
Error when running BouncingBall example

### ISSUE THREAD

**Issue by Sciemon** [ThummeTo/FMIExport.jl#37]
When I try to run the bouncing ball example from [here](https://github.com/ThummeTo/FMIExport.jl/blob/examples/examples/BouncingBall.jl), I get the error message below. Disclaimer: I am new to Julia :)

I am on Julia 1.9 on windows.

ERROR: BoundsError: attempt to access Tuple{Float64, Vector{Float64}, Vector{Float64}, Vector{Any}, Vector{Float64}} at index [6]
Stacktrace:
 [1] indexed_iterate(t::Tuple{Float64, Vector{Float64}, Vector{Float64}, Vector{Any}, Vector{Float64}}, i::Int64, state::Int64)
   @ Base .\tuple.jl:88
 [2] fmi2CreateSimple(; initializationFct::Function, evaluationFct::Function, outputFct::Function, eventFct::Function)
   @ FMIExport C:\Users\seberlein\.julia\packages\FMIExport\j8bGN\src\FMI2_simple.jl:548
 [3] (::var"#51#52")(resPath::String)
   @ Main d:\User\seberlein\Julia\FMI\bouncing_ball_example_from_github_FMIExport.jl:80
 [4] (::var"#51#52")()
   @ Main d:\User\seberlein\Julia\FMI\bouncing_ball_example_from_github_FMIExport.jl:80
 [5] top-level scope
   @ d:\User\seberlein\Julia\FMI\bouncing_ball_example_from_github_FMIExport.jl:111

**Comment by Sciemon** [comment]
Update: I'm not sure this is the latest version of the example (the link in the docs is not up to date).
I also tried examples/FMI2/BouncingBall/src/BouncingBall.jl

This gives the following error:

[ Info: Saving example files at: C:\Users\seberlein\AppData\Local\Temp\fmibuildjl_test_4FzTmL
[ Info: [Build FMU] Automatically determined build file at: `d:\User\seberlein\Julia\FMI\bouncing_ball_example_from_github_FMIExport.jl`.
[ Info: [Build FMU] Generating package ...
ERROR: AssertionError: ["fmiBuild(...): Cannot find a package where this file is stored in. For FMU-Export, this source file needs to be inside of a package."]
Stacktrace:
 [1] fmi2Save(fmu::FMICore.FMU2, fmu_path::String, fmu_src_file::Nothing; standalone::Bool, compress::Bool, cleanup::Bool, removeLibDependency::Bool, removeNoExportBlocks::Bool, resources::Nothing, debug::Bool, surpressWarnings::Bool, pkg_comp_kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ FMIBuild C:\Users\seberlein\.julia\packages\FMIBuild\hYVfv\src\FMIBuild.jl:182
 [2] fmi2Save
   @ C:\Users\seberlein\.julia\packages\FMIBuild\hYVfv\src\FMIBuild.jl:70 [inlined]
 [3] top-level scope
   @ d:\User\seberlein\Julia\FMI\bouncing_ball_example_from_github_FMIExport.jl:143

**Comment by ThummeTo** [comment]
Seems like the examples branch wasn't updated because a failing action, please find the most recent version of the example [here](https://github.com/ThummeTo/FMIExport.jl/blob/main/examples/FMI2/BouncingBall/src/BouncingBall.jl) - this one should work!

**Comment by Sciemon** [comment]
thank you for the fast response. I also found this example in the meantime. However it gives me the error message from my second comment.

**Comment by ThummeTo** [comment]
Hmmmmm, I can't reproduce the error, if I start with a fresh Julia 1.9.3 and FMIExport.jl v0.3.1 and run the following line
`include("C:\\...\\FMIExport.jl\\examples\\FMI2\\BouncingBall\\src\\BouncingBall.jl")`
(which is the same as executing it in VSCode), the script runs and the FMU compiles.

BTW: I corrected the examples link in the readme to point to the new examples.

**Comment by Sciemon** [comment]
yes, it took me some time to understand the error message correctly, my bad

**Comment by ThummeTo** [comment]
No problem!

**Comment by ThummeTo** [comment]
I can improve the error message, too.

**Comment by ThummeTo** [comment]
Just check if it compiles now and if yes don't forget to close the issue ;-)

**Comment by Sciemon** [comment]
It has compiled after a while and I was able to run the simulation. Thanks again for the help. I will try my luck now with my own first (very simple) example :) Nice package!
